## this file for accessing data from dataset and scraped dataset

In [2]:
import json
import pandas as pd
import numpy as np

In [9]:
ratings = pd.read_csv("/DATA/punitsingh1801/prabir/prabir/python_program/Earl_workshop/GoT/data/ratings.dat", sep="::", engine="python")
ratings.columns = ["used.read_csvr_id", "movie_id", "rating", "timestamp"]

# # print(f"total ratings = {len(ratings)}")
# # ratings.head()

In [3]:

def read_json_file(filepath):
    """Reads a JSON file and returns the data as a Python object (dict or list)."""
    try:
        with open(filepath, 'r') as file:
            data = json.load(file)
        return data
    except FileNotFoundError:
        print(f"Error: File not found at {filepath}")
        return None
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in {filepath}")
        return None

In [14]:
# All Users

user_file = '/DATA/punitsingh1801/prabir/prabir/python_program/Earl_workshop/GoT/data/users.json'
user_file = read_json_file(user_file)


all_users = []
for u_id in list(user_file.keys()):
    dic = {"user_id": u_id, **user_file[u_id]}
    all_users.append(dic)
    
all_users = pd.DataFrame(all_users)
print(f"total users = {len(all_users)}")

total users = 6040

In [15]:
all_users.head()

  user_id Gender Age Occupation Zip-code
0       1      F   1         10    48067
1       2      M  56         16    70072
2       3      M  25         15    55117
3       4      M  45          7    02460
4       5      M  25         20    55455

In [18]:

# All Movies

movie_file = '/DATA/punitsingh1801/prabir/prabir/python_program/Earl_workshop/GoT/data/movies.json'
movie_file = read_json_file(movie_file)


all_movies = []
for m_id in list(movie_file.keys()):
    dic = {"movie_id": m_id, **movie_file[m_id]}
    all_movies.append(dic)
    
all_movies = pd.DataFrame(all_movies)

print(f"total movies = {len(all_movies)}")
# all_movies.head()

total movies = 4889

In [19]:
## All Movies

clusters_file = '/DATA/punitsingh1801/prabir/prabir/python_program/Earl_workshop/GoT/data/clusters.json'
clusters_file = read_json_file(clusters_file)

all_cluster = []
for user in clusters_file:
    keys = list(user.keys())
    user_id = int(user[keys[0]])
    user_clusters = user[keys[1]]

    for user_cluster in user_clusters:
       
        cluster = {"user_id": user_id, **user_cluster}
        all_cluster.append(cluster)
        
all_cluster = pd.DataFrame(all_cluster)
all_cluster = all_cluster.sort_values(by=["user_id", "clusterID"])

print(f"total user_clusters = {len(all_cluster)}")

total user_clusters = 34805

In [20]:
all_cluster.head()

   user_id clusterID                                          movie_ids
0        1         0  [4144, 1765, 1527, 3336, 1704, 4064, 145, 1533...
1        1         1  [2750, 4359, 792, 3873, 3033, 1445, 2967, 3023...
5        2         0  [3693, 3909, 2967, 773, 1859, 2593, 1874, 2722...
3        2         1                       [1707, 1693, 4211, 342, 286]
4        2         2  [1714, 1591, 3999, 107, 1754, 3703, 1604, 1625...

"User Details: 
gender: Male, age: between 18 to 24, occupation: college/grad student

Movie Details:
movie name: Matrix, The (1999), genres:  Action|Sci-Fi|Thriller
storyline: Thomas A. Anderson is a man living two lives. By day, he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion.

Rating Given to the Movie: 4/ 5 where 5 means likes the movie the most and 1 means dislikes the movie."

Here are the user details, movie details and the rating given to the movie by the user have been mentioned. Now please read the information and finally answer me the following question by covering all the steps,
Question: What is the preference of the user?
Steps to follow to answer my question:
1. Please analyse the movie features by considering the user's data and find the movie features that suit the user's gender, occupation, and age.
2. As per the user's age, occupation, please analyse and find out what might be the movie features for which the user has rated 4 out of 5? 
3. As per the user details (age, occupation) please analyse and find out what might be movie features for which the user has not rated 5 out of 5 to the movie.
4.  As per the user details, movie details, the rating given to the movie  and the analysis from the above two points, please analyse and find out the user preference by concerning both user and movie details. Please analyse user preference from  both sides like what he likes and what he dislikes.
5. Now, finally answer me. Please highlight all the points that describe user preferences in both positive and negative aspects. 

answer the above question by following the steps  in the following dictionary format,
{"What he likes":
{"Feature 1": one line description,
"Feature 2": one-line description,
"Feature 3": one-line description,
},

"What he dislikes":
{"Feature 1": one-line description,
"Feature 2": one-line description,
"Feature 3": one-line description,
}
}

Add as many features as required. Please give the appropriate feature name instead of "Feature 1". Use a maximum of two words in the feature name. Only share the final answer.

## read the movie reviews

In [19]:
# All Users

movie_imdb_id_file = '/DATA/punitsingh1801/prabir/prabir/python_program/Earl_workshop/GoT/data/imdb_id_map.json'
movie_imdb_id_file = read_json_file(movie_imdb_id_file)


all_movies = []
for m_id in list(movie_imdb_id_file.keys()):
    # print(m_id)
    dic = (movie_imdb_id_file[m_id])
    all_movies.append(dic)
    
all_movies = pd.DataFrame(all_movies)
print(f"total users = {len(all_movies)}")

total users = 3719

In [45]:
# all_movies.head()

In [46]:
# All reviews

review_file = '/DATA/punitsingh1801/prabir/prabir/python_program/Earl_workshop/GoT/data/movie_reviews/grouped_reviews.json/grouped_reviews.json'
review_file = read_json_file(review_file)

all_movie_reviews = []
for m_id in list(review_file.keys()):
    for review in review_file[m_id]:
        r = {"movie_id": m_id, **review}
        all_movie_reviews.append(r)

all_movie_reviews = pd.DataFrame(all_movie_reviews)
# all_movie_reviews.head()

In [47]:
reviews = pd.merge(all_movies, all_movie_reviews, right_on="movie_id", left_on="imdb_id", how="left")

In [48]:
reviews = reviews.iloc[:, [0, 1, 2, 3, 5, 6, 7, 9]]
reviews = reviews.rename(columns={"movie_id_x": "movie_id"}) # rename column names
reviews = reviews[["movie_id", "imdb_id", "original_title", "clean_title", "review_title", "review_rating", "review_text", "review_date"]] # reorder the columns

In [51]:
# reviews.head()

In [50]:
reviews.to_csv("movie_reviews.csv", index=False)